name: CI

on:
  push:
    branches:
      - next
      - V3.0
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  lint:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable pnpm

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm lint

  test:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable pnpm

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run test
        run: pnpm test

      - name: Upload coverage reports to Codecov
        if: ${{ always() }}
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable pnpm

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build NutUI-React
        run: pnpm build

      - name: Build NutUI-React-Taro
        run: pnpm build:taro

      - name: Build NutUI-React Demo
        run: pnpm build:site

      - name: Build NutUI-React Taro H5 Demo
        if: github.ref == 'refs/heads/next'
        run: pnpm build:taro:site
  add-label:
    if: ${{ github.event_name == 'pull_request_target' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Determine label based on target branch
        id: determine-label
        run: |
          echo "${{github.event_name}}"
          if [[ "${{ github.event.pull_request.base.ref }}" == "next" ]]; then
            echo "label=2.x" >> $GITHUB_ENV
          elif [[ "${{ github.event.pull_request.base.ref }}" == "V3.0" ]]; then
            echo "label=3.x" >> $GITHUB_ENV
          else
            echo "label=" >> $GITHUB_ENV
          fi

      - name: Add label to Pull Request
        if: env.label != ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.label }}